#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Damit dies funktioniert: git config core.hooksPath .githooks

files_to_check="main.css Kurzmeldungen-archive.js eisschnelllauf-events.js generalFunctions.js oeffentlicheMeldungen.js wettbewerbe-data.js formularBedingungen.js"
failed=0
staged_files=$(git diff --cached --name-only)
for file in $files_to_check; do
    if echo "$staged_files" | grep -q "$file"; then
        echo ""
        echo "==============================================================="
        echo "   ACHTUNG: Aenderungen in $file!"
        echo "   In HTML Dateien, sucht nach $file?v=N &"
        echo "   aendert die Stellen auf $file?v=N+1"
        echo "==============================================================="
        echo ""
        failed=1
    fi
done

if [ "$failed" -eq 1 ]; then
    exit 1
fi

